import { encodeQr } from "@lms/shared";
import { A4, Page, buildPdf, textWidth, type FontName } from "./pdf";

/**
 * THE FEE RECEIPT — the one thing in this System that leaves the building.
 *
 * A student hands over money and gets a piece of paper. That paper is the
 * Institute's written admission that it holds the money, and it is what they
 * produce when somebody later says it never arrived. So it is laid out as a
 * financial document and not as a screen: a masthead, a ruled body, one figure
 * that dominates, the amount repeated in words, a signature block, and a
 * footer that says who issued it and how to check it.
 *
 * IT IS NOT A DASHBOARD CARD. No rounded corners, no soft shadows, no pastel
 * status chips, nothing that reads as an interface. Those things say
 * "generated by software"; a receipt has to say "issued by an institution".
 * The whole palette is one ink, one rule colour and the Institute's navy — and
 * the accent is used for one thing only, the band behind the amount.
 *
 * IT PRINTS IN BLACK AND WHITE. Every distinction that carries meaning — the
 * status, the reversal, the duplicate mark — is a WORD as well as a colour
 * (NFR-ACC-007), because a receipt is photocopied more often than it is
 * looked at on a screen.
 *
 * THE SAME DATA MAKES BOTH FACES. `ReceiptDocument` is what the API returns to
 * the screen and what this file sets in the PDF, so the paper a student
 * downloads and the page they were looking at cannot disagree — which is the
 * single most damaging thing a receipt system can do.
 */

export interface ReceiptDocument {
  receiptNo: string;
  issuedAt: Date;
  /** True when this print is not the first. Stated on the face of it. */
  reprint: boolean;
  /** VERIFIED, or REVERSED. There is no third state on a receipt. */
  status: "VERIFIED" | "REVERSED";

  institute: {
    name: string;
    campus: string;
    phone: string;
    email: string;
    website: string;
  };

  student: {
    fullName: string;
    registrationNo: string;
    programme: string | null;
    section: string | null;
    rollNo: number | null;
  };

  payment: {
    id: string;
    amount: number;
    currency: string;
    amountInWords: string;
    paidOn: Date;
    method: string;
    methodLabel: string;
    bankReference: string | null;
    /** The claim this came from, when a student submitted one. */
    submissionReference: string | null;
  };

  verification: {
    verifiedBy: string;
    verifiedAt: Date;
    note: string | null;
  };

  /** Present only when the payment has been reversed. */
  reversal: { reversedAt: Date; reason: string | null } | null;

  /**
   * The student's position at the moment this receipt was issued.
   *
   * `before` and `after` are the two figures a receipt is actually read for:
   * "what did I owe, and what do I owe now". Null when the ledger cannot be
   * stated — a receipt must never print a confident zero it did not compute.
   */
  ledger: {
    totalFee: number;
    previouslyPaid: number;
    thisPayment: number;
    balanceAfter: number;
  } | null;

  /** Where a holder can check this receipt against the Institute's record. */
  verifyUrl: string | null;
  note: string;
}

// ------------------------------------------------------------- palette ----
// Three inks and a rule. Brand Guidelines V2.0 §3.1: navy carries it, amber is
// the single accent, and nothing else appears.
const NAVY: readonly [number, number, number] = [0.102, 0.235, 0.369];
const INK: readonly [number, number, number] = [0.067, 0.094, 0.153];
const SOFT: readonly [number, number, number] = [0.38, 0.42, 0.48];
const RULE: readonly [number, number, number] = [0.78, 0.82, 0.87];
const AMBER: readonly [number, number, number] = [0.961, 0.651, 0.137];
const PALE: readonly [number, number, number] = [0.949, 0.961, 0.973];
const RED: readonly [number, number, number] = [0.725, 0.11, 0.11];
const WHITE: readonly [number, number, number] = [1, 1, 1];

const MARGIN = 48;
const CONTENT = A4.width - MARGIN * 2;

/** The Institute writes money grouped, and never abbreviated. */
function money(amount: number, currency: string): string {
  const whole = Number.isInteger(amount);
  const body = Math.abs(amount).toLocaleString("en-PK", {
    minimumFractionDigits: whole ? 0 : 2,
    maximumFractionDigits: 2,
  });
  const sign = amount < 0 ? "-" : "";
  return currency === "PKR" ? `${sign}Rs ${body}` : `${sign}${currency} ${body}`;
}

/** A date on a document is spelled out. "03/04/26" is three different days. */
function longDate(d: Date): string {
  return d.toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
}

function dateAndTime(d: Date): string {
  return `${longDate(d)} at ${d.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })}`;
}

/**
 * The PDF.
 *
 * ONE PAGE, ALWAYS. A receipt that breaks across two sheets is two half
 * documents, and the half without the amount on it proves nothing. Everything
 * here is sized so the longest realistic content still fits: the fields are
 * fixed rows, the only wrapping text is the footer note and the reversal
 * reason, and both have a hard ceiling.
 */
export function renderReceiptPdf(r: ReceiptDocument): Buffer {
  const page = new Page();
  let y = 0;

  y = masthead(page, r);
  y = titleBar(page, r, y);
  y = parties(page, r, y);
  y = amountBand(page, r, y);
  y = ledgerTable(page, r, y);
  verificationBlock(page, r, y);
  signatures(page, r);
  footer(page, r);

  // Drawn LAST so it lies over the document rather than under it, which is
  // what makes a duplicate impossible to photocopy away.
  if (r.status === "REVERSED") {
    page.rotatedText("REVERSED", 132, 560, 32, { size: 78, colour: [0.96, 0.86, 0.86] });
  } else if (r.reprint) {
    page.rotatedText("DUPLICATE", 118, 570, 32, { size: 68, colour: [0.925, 0.937, 0.949] });
  }

  return buildPdf([page], {
    title: `Fee Receipt ${r.receiptNo}`,
    author: r.institute.name,
  });
}

/** The Institute's name, and how to reach it. The letterhead. */
function masthead(page: Page, r: ReceiptDocument): number {
  // A navy band across the head. It is the one large area of colour on the
  // page and it does the work a printed letterhead does: it says at a glance,
  // from across a desk, which institution issued this.
  page.rect(0, 0, A4.width, 4, AMBER);
  page.rect(0, 4, A4.width, 84, NAVY);

  // The emblem, drawn rather than embedded: a monogram in a ruled square. An
  // image would mean a second storage read on a path that must not fail, and a
  // logo that is missing from a receipt looks worse than one that was never
  // there.
  const mark = MARGIN;
  page.frame(mark, 24, 44, 44, [1, 1, 1], 1.2);
  page.text(initialsOf(r.institute.name), mark, 54, {
    font: "Helvetica-Bold",
    size: 19,
    colour: WHITE,
    align: "center",
    width: 44,
  });

  page.text(r.institute.name, mark + 60, 44, {
    font: "Helvetica-Bold",
    size: 17,
    colour: WHITE,
  });

  const contact = [r.institute.campus, r.institute.phone, r.institute.email, r.institute.website]
    .map((s) => s.trim())
    .filter(Boolean)
    .join("   ·   ");
  if (contact) {
    page.text(contact, mark + 60, 62, { size: 8.2, colour: [0.78, 0.84, 0.9] });
  }

  page.text("OFFICIAL FEE RECEIPT", mark + 60, 76, {
    size: 7.4,
    colour: AMBER,
    tracking: 1.6,
    font: "Helvetica-Bold",
  });

  return 88;
}

/**
 * The receipt number and the status, side by side under the masthead.
 *
 * THE NUMBER IS THE SECOND MOST IMPORTANT THING ON THE PAGE, after the amount,
 * because it is what both parties quote when they disagree. It gets its own
 * ruled box on the right where a reader's eye goes for a reference.
 */
function titleBar(page: Page, r: ReceiptDocument, top: number): number {
  const y = top + 26;

  page.text("Fee Payment Receipt", MARGIN, y + 6, {
    font: "Helvetica-Bold",
    size: 20,
    colour: INK,
  });
  page.text(
    r.status === "REVERSED"
      ? "This payment has since been reversed. See the notice below."
      : "This confirms payment received and verified by the Institute.",
    MARGIN,
    y + 24,
    { size: 9, colour: SOFT },
  );

  // The reference box.
  const boxW = 186;
  const boxX = A4.width - MARGIN - boxW;
  page.rect(boxX, top + 14, boxW, 56, PALE);
  page.rect(boxX, top + 14, 3, 56, r.status === "REVERSED" ? RED : NAVY);

  page.text("RECEIPT NO.", boxX + 14, top + 30, {
    size: 6.8,
    colour: SOFT,
    tracking: 1.1,
    font: "Helvetica-Bold",
  });
  page.text(r.receiptNo, boxX + 14, top + 46, { font: "Helvetica-Bold", size: 14, colour: INK });
  page.text(`Issued ${longDate(r.issuedAt)}`, boxX + 14, top + 60, { size: 8, colour: SOFT });

  if (r.reprint) {
    page.text("DUPLICATE COPY", boxX + 14, top + 82, {
      size: 7.4,
      colour: RED,
      tracking: 0.8,
      font: "Helvetica-Bold",
    });
  }

  return top + (r.reprint ? 96 : 84);
}

/** Who paid, and what for. Two columns, so neither is scanned past. */
function parties(page: Page, r: ReceiptDocument, top: number): number {
  const y = top + 8;
  page.line(MARGIN, y, A4.width - MARGIN, y, RULE, 1);

  const colW = (CONTENT - 24) / 2;
  const leftX = MARGIN;
  const rightX = MARGIN + colW + 24;

  sectionLabel(page, "RECEIVED FROM", leftX, y + 20);
  sectionLabel(page, "TOWARDS", rightX, y + 20);

  let ly = y + 40;
  ly = field(page, leftX, ly, colW, "Student", r.student.fullName, true);
  ly = field(page, leftX, ly, colW, "Registration no.", r.student.registrationNo, true);
  if (r.student.rollNo !== null) {
    ly = field(page, leftX, ly, colW, "Roll no.", String(r.student.rollNo));
  }

  let ry = y + 40;
  ry = field(page, rightX, ry, colW, "Course", r.student.programme ?? "Not recorded");
  ry = field(page, rightX, ry, colW, "Batch", r.student.section ?? "Not recorded");
  ry = field(page, rightX, ry, colW, "Paid on", longDate(r.payment.paidOn), true);

  const bottom = Math.max(ly, ry);
  page.line(MARGIN, bottom + 2, A4.width - MARGIN, bottom + 2, RULE, 0.6);
  return bottom + 2;
}

/**
 * THE AMOUNT. The one thing a reader must not be able to miss.
 *
 * Set large, on a band, with the words underneath. The words are not
 * decoration: they are the ordinary defence against a digit being added to a
 * printed line, and every receipt book in the country carries them.
 */
function amountBand(page: Page, r: ReceiptDocument, top: number): number {
  const bandTop = top + 18;
  const bandH = 76;

  page.rect(MARGIN, bandTop, CONTENT, bandH, NAVY);
  page.rect(MARGIN, bandTop, 5, bandH, AMBER);

  page.text("AMOUNT RECEIVED", MARGIN + 22, bandTop + 22, {
    size: 7.2,
    colour: [0.72, 0.79, 0.87],
    tracking: 1.4,
    font: "Helvetica-Bold",
  });

  page.text(money(r.payment.amount, r.payment.currency), MARGIN + 22, bandTop + 50, {
    font: "Helvetica-Bold",
    size: 27,
    colour: WHITE,
  });

  page.text(r.payment.amountInWords, MARGIN + 22, bandTop + 66, {
    font: "Times-Italic",
    size: 9.6,
    colour: [0.82, 0.87, 0.92],
  });

  // The method and reference sit on the right of the band, because the two
  // questions a reader has after "how much" are "how" and "which transaction".
  const rightEdge = A4.width - MARGIN - 22;
  const w = 200;
  page.text("METHOD", rightEdge - w, bandTop + 22, {
    size: 7.2,
    colour: [0.72, 0.79, 0.87],
    tracking: 1.4,
    font: "Helvetica-Bold",
    align: "right",
    width: w,
  });
  page.text(r.payment.methodLabel, rightEdge - w, bandTop + 38, {
    font: "Helvetica-Bold",
    size: 11.5,
    colour: WHITE,
    align: "right",
    width: w,
  });
  if (r.payment.bankReference) {
    page.text(`Ref. ${r.payment.bankReference}`, rightEdge - w, bandTop + 53, {
      size: 8.6,
      colour: [0.82, 0.87, 0.92],
      align: "right",
      width: w,
    });
  }
  if (r.payment.submissionReference) {
    page.text(`Submission ${r.payment.submissionReference}`, rightEdge - w, bandTop + 66, {
      size: 8,
      colour: [0.66, 0.74, 0.83],
      align: "right",
      width: w,
    });
  }

  return bandTop + bandH;
}

/**
 * The student's account, before and after.
 *
 * WHY IT IS ON THE RECEIPT AT ALL. The question a student asks the moment they
 * are handed one is "so what do I still owe" — and if the paper does not
 * answer it they telephone the office, which is the cost this whole feature
 * exists to remove. Four rows, ruled, with the balance emphasised.
 */
function ledgerTable(page: Page, r: ReceiptDocument, top: number): number {
  if (!r.ledger) return top;

  const y = top + 26;
  sectionLabel(page, "YOUR FEE ACCOUNT AFTER THIS PAYMENT", MARGIN, y);

  const rows: Array<[string, number, boolean]> = [
    ["Total fee for the course", r.ledger.totalFee, false],
    ["Paid and verified before this", r.ledger.previouslyPaid, false],
    ["This payment", r.ledger.thisPayment, false],
    ["Balance still to pay", r.ledger.balanceAfter, true],
  ];

  const rowH = 19;
  let rowTop = y + 10;
  const amountW = 150;
  const amountX = A4.width - MARGIN - amountW - 12;

  rows.forEach(([label, value, emphasis], i) => {
    if (emphasis) {
      page.rect(MARGIN, rowTop, CONTENT, rowH, PALE);
    } else if (i % 2 === 1) {
      page.rect(MARGIN, rowTop, CONTENT, rowH, [0.985, 0.99, 0.995]);
    }
    page.text(label, MARGIN + 12, rowTop + 13, {
      size: emphasis ? 10 : 9.4,
      font: emphasis ? "Helvetica-Bold" : "Helvetica",
      colour: emphasis ? INK : [0.25, 0.3, 0.36],
    });
    page.text(money(value, r.payment.currency), amountX, rowTop + 13, {
      size: emphasis ? 11 : 9.8,
      font: emphasis ? "Helvetica-Bold" : "Helvetica",
      colour: emphasis ? NAVY : INK,
      align: "right",
      width: amountW,
    });
    page.line(MARGIN, rowTop + rowH, A4.width - MARGIN, rowTop + rowH, RULE, 0.4);
    rowTop += rowH;
  });

  page.frame(MARGIN, y + 10, CONTENT, rowH * rows.length, RULE, 0.7);

  if (r.ledger.balanceAfter <= 0.005) {
    page.text("Paid in full. Nothing further is owed on this account.", MARGIN, rowTop + 14, {
      size: 8.8,
      colour: [0.024, 0.373, 0.275],
      font: "Helvetica-Bold",
    });
    rowTop += 8;
  }

  return rowTop + 6;
}

/** Who checked it, when, and the notice if it was later undone. */
function verificationBlock(page: Page, r: ReceiptDocument, top: number): number {
  let y = top + 24;

  if (r.reversal) {
    // A framed notice rather than a line of prose. Somebody holding this piece
    // of paper as proof of a payment must not be able to skim past the fact
    // that the Institute no longer holds the money.
    //
    // THE BOX IS MEASURED, NOT ASSUMED. It was a fixed 46 points, and a reason
    // of any length pushed the last line of the warning outside its own frame
    // — the one sentence on the receipt that must not look like a mistake.
    // The reason is capped as well, because a paragraph typed into a rejection
    // box has no natural ceiling and this document has one page.
    const body =
      `Reversed on ${longDate(r.reversal.reversedAt)}.` +
      (r.reversal.reason ? ` ${clip(r.reversal.reason, 220)}` : "") +
      " This receipt is kept so the record is complete. It is not proof of a payment the" +
      " Institute holds.";

    const leading = 10.5;
    const lines = page.countLines(body, CONTENT - 24, "Helvetica", 8.4);
    const h = 26 + lines * leading;

    page.frame(MARGIN, y, CONTENT, h, RED, 1.1);
    page.text("PAYMENT REVERSED", MARGIN + 12, y + 17, {
      font: "Helvetica-Bold",
      size: 10,
      colour: RED,
      tracking: 0.6,
    });
    page.paragraph(body, MARGIN + 12, y + 30, CONTENT - 24, {
      size: 8.4,
      colour: INK,
      leading,
    });
    y += h + 14;
  }

  sectionLabel(page, "VERIFICATION", MARGIN, y);
  const colW = (CONTENT - 24) / 2;
  let ly = y + 20;
  ly = field(page, MARGIN, ly, colW, "Status", r.status === "REVERSED" ? "Reversed" : "Verified", true);
  ly = field(page, MARGIN, ly, colW, "Verified by", r.verification.verifiedBy || "The office");

  let ry = y + 20;
  ry = field(page, MARGIN + colW + 24, ry, colW, "Verified on", dateAndTime(r.verification.verifiedAt), true);
  if (r.verification.note) {
    ry = field(page, MARGIN + colW + 24, ry, colW, "Remarks", r.verification.note);
  }

  return Math.max(ly, ry);
}

/**
 * The signature block and the QR.
 *
 * PINNED TO THE BOTTOM rather than flowing after the content, because a
 * signature line that floats up the page when the content is short reads as an
 * unfinished document. A receipt has a foot, and the foot is where it is.
 */
function signatures(page: Page, r: ReceiptDocument): void {
  const base = A4.height - 122;

  if (r.verifyUrl) {
    // Placed with the signatures rather than in a corner: the point of the
    // code is that somebody checking the document does it while they are
    // looking at the part that claims authority.
    const size = 62;
    const x = MARGIN;
    try {
      page.qr(encodeQr(r.verifyUrl), x, base - 30, size, INK);
    } catch {
      // A URL longer than the encoder's ceiling. The receipt is still a
      // receipt; it simply loses the shortcut, and the printed number below is
      // what a person checks with anyway.
    }
    page.text("Scan to verify", x, base + 42, { size: 7, colour: SOFT });
  }

  const signW = 190;
  const signX = A4.width - MARGIN - signW;
  page.line(signX, base + 18, signX + signW, base + 18, INK, 0.8);
  page.text("Authorised signature and stamp", signX, base + 30, {
    size: 7.8,
    colour: SOFT,
    align: "center",
    width: signW,
  });

  const midW = 170;
  const midX = signX - midW - 24;
  page.line(midX, base + 18, midX + midW, base + 18, INK, 0.8);
  page.text(r.verification.verifiedBy || "The office", midX, base + 14, {
    size: 9,
    colour: INK,
    align: "center",
    width: midW,
  });
  page.text("Received by", midX, base + 30, {
    size: 7.8,
    colour: SOFT,
    align: "center",
    width: midW,
  });
}

function footer(page: Page, r: ReceiptDocument): void {
  const y = A4.height - 60;
  page.line(MARGIN, y, A4.width - MARGIN, y, RULE, 0.6);

  page.paragraph(r.note, MARGIN, y + 14, CONTENT - 150, { size: 7.8, colour: SOFT, leading: 9.5 });

  const stamp = `${r.receiptNo}  ·  generated ${dateAndTime(new Date())}`;
  page.text(stamp, A4.width - MARGIN - 260, A4.height - 26, {
    size: 6.8,
    colour: SOFT,
    align: "right",
    width: 260,
  });
  if (r.verifyUrl) {
    page.text(r.verifyUrl, MARGIN, A4.height - 26, { size: 6.8, colour: SOFT });
  }

  page.rect(0, A4.height - 5, A4.width, 5, NAVY);
}

// ---------------------------------------------------------------- parts ----

/** A small tracked-out heading. The only typographic ornament on the page. */
function sectionLabel(page: Page, text: string, x: number, baseline: number): void {
  page.text(text, x, baseline, {
    size: 6.9,
    colour: NAVY,
    tracking: 1.2,
    font: "Helvetica-Bold",
  });
}

/**
 * A label above its value, returning the next baseline.
 *
 * Label ABOVE rather than beside, because the values here vary from "3" to a
 * forty-character course name, and a two-column layout either wraps the long
 * ones or wastes half the page on the short ones. A long value is truncated
 * with an ellipsis rather than allowed to run into the next column — a course
 * name that overlaps the amount is worse than one that is shortened.
 */
function field(
  page: Page,
  x: number,
  baseline: number,
  width: number,
  label: string,
  value: string,
  emphasis = false,
): number {
  page.text(label, x, baseline, { size: 7.6, colour: SOFT });
  const font: FontName = emphasis ? "Helvetica-Bold" : "Helvetica";
  const size = emphasis ? 10.6 : 10;
  page.text(truncate(value, width, font, size), x, baseline + 14, { font, size, colour: INK });
  return baseline + 32;
}

/** A hard ceiling on free text, so one page stays one page. */
function clip(text: string, max: number): string {
  return text.length <= max ? text : `${text.slice(0, max - 1).trimEnd()}...`;
}

function truncate(text: string, width: number, font: FontName, size: number): string {
  if (textWidth(text, font, size) <= width) return text;
  let cut = text;
  while (cut.length > 1 && textWidth(`${cut}...`, font, size) > width) cut = cut.slice(0, -1);
  return `${cut}...`;
}

/**
 * The monogram in the masthead square.
 *
 * At most three letters — "PPS" reads as a mark, "TPIOTT" reads as a mistake.
 */
function initialsOf(name: string): string {
  const letters = name
    .split(/\s+/)
    .filter((w) => /^[A-Za-z]/.test(w) && !["of", "the", "and", "for"].includes(w.toLowerCase()))
    .map((w) => w[0]!.toUpperCase());
  return letters.slice(0, 3).join("") || "I";
}
