/**
 * CSV export — SRS FR-RPT-004, FR-RPT-005.
 *
 * A pure function so the escaping can be tested directly. CSV escaping looks
 * trivial and is not: a student named O'Brien, an address containing a comma,
 * or a feedback comment containing a newline will each corrupt a naive
 * implementation, and the corruption is silent — the file opens, it is simply
 * wrong.
 */

export interface CsvColumn<T> {
  header: string;
  value: (row: T) => unknown;
}

export interface CsvMeta {
  reportName: string;
  generatedBy: string;
  generatedAt: Date;
  /** FR-RPT-003 — the filters actually applied, echoed into the file. */
  filters?: Record<string, unknown>;
  institute?: string;
}

/**
 * Escapes one field per RFC 4180.
 *
 * The leading apostrophe on formula-like values is deliberate: a cell starting
 * with =, +, - or @ is executed by Excel on open, so a registration number
 * entered as "=cmd|..." becomes a CSV injection attack against whoever opens
 * the export. Prefixing neutralises it while leaving the value readable.
 */
export function escapeCsvField(value: unknown): string {
  if (value === null || value === undefined) return "";

  let s: string;
  if (value instanceof Date) {
    s = value.toISOString();
  } else if (typeof value === "object") {
    s = JSON.stringify(value);
  } else {
    s = String(value);
  }

  if (/^[=+\-@\t\r]/.test(s)) s = `'${s}`;

  if (/[",\r\n]/.test(s)) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

/**
 * Builds a CSV document with the provenance header FR-RPT-005 requires.
 *
 * A report emailed onward without its filters is unreadable a week later:
 * nobody can tell whether "412 students" meant all of them or one section.
 */
export function buildCsv<T>(rows: T[], columns: Array<CsvColumn<T>>, meta: CsvMeta): string {
  const lines: string[] = [];

  lines.push(escapeCsvField(meta.institute ?? "Institute"));
  lines.push(escapeCsvField(meta.reportName));
  lines.push(`${escapeCsvField("Generated")},${escapeCsvField(meta.generatedAt)}`);
  lines.push(`${escapeCsvField("Generated by")},${escapeCsvField(meta.generatedBy)}`);

  if (meta.filters && Object.keys(meta.filters).length > 0) {
    const applied = Object.entries(meta.filters)
      .filter(([, v]) => v !== undefined && v !== null && v !== "")
      .map(([k, v]) => `${k}=${String(v)}`)
      .join("; ");
    lines.push(`${escapeCsvField("Filters")},${escapeCsvField(applied || "none")}`);
  }

  lines.push(`${escapeCsvField("Rows")},${escapeCsvField(rows.length)}`);
  lines.push(""); // separates provenance from data

  lines.push(columns.map((c) => escapeCsvField(c.header)).join(","));
  for (const row of rows) {
    lines.push(columns.map((c) => escapeCsvField(c.value(row))).join(","));
  }

  if (rows.length === 0) {
    // FR-RPT-020 — an empty grid looks like a broken report. Say so.
    lines.push("");
    lines.push(escapeCsvField("No records matched these filters."));
  }

  // CRLF per RFC 4180, and a BOM so Excel reads UTF-8 rather than mangling
  // non-Latin names (NFR-LOC-004).
  return "﻿" + lines.join("\r\n") + "\r\n";
}

/** A filename that sorts chronologically and is safe on every filesystem. */
export function csvFilename(reportKey: string, at = new Date()): string {
  const stamp = at.toISOString().slice(0, 19).replace(/[:T]/g, "-");
  return `${reportKey.replace(/[^a-z0-9-]/gi, "-")}-${stamp}.csv`;
}
